### ISSUE TITLE
Server Side Connection Drops Immediately

### ISSUE THREAD

**Issue by pass-by-value** [Lawouach/WebSocket-for-Python#134]
Hi,

I'm facing an issue trying to establish a secure websocket connection. It looks like the server side websocket connection gets dropped immediately.

Following logger output shows up when I make a connection using Firefox.

```
[INFO    ] Managing websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:57153]
[INFO    ] Terminating websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:57153]
```

I used the following code to establish the websocket connection. (I have SSL enabled on my server)

``` javascript
var ws = new WebSocket('wss://localhost:8000/all_events/89e9c2ae3f1db4d9952b2a1a6c84bc2b2acf6e2a')
```

When I connect using Google Chrome the "Managing websocket" message shows up but there is no "Terminating" message. But, when the server side websocket tries to send data to the client I see the following error.

```
Traceback (most recent call last):
  File "/Users/adi/Envs/salt-work/lib/python2.7/site-packages/ws4py/websocket.py", line 300, in once
    b = self.sock.recv(self.reading_buffer_size)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1426: error:140943FC:SSL routines:SSL3_READ_BYTES:sslv3 alert bad record mac

[INFO    ] Terminating websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:57031]
Process Process-1:2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adi/salt-api/saltapi/netapi/rest_cherrypy/app.py", line 1677, in event_stream
    handler.send('data: {0}\n\n'.format(json.dumps(data)), False)
  File "/Users/adi/Envs/salt-work/lib/python2.7/site-packages/ws4py/websocket.py", line 261, in send
    self._write(m)
  File "/Users/adi/Envs/salt-work/lib/python2.7/site-packages/ws4py/websocket.py", line 243, in _write
    self.sock.sendall(b)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 229, in sendall
    v = self.send(data[count:])
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 198, in send
    v = self._sslobj.write(data)
error: [Errno 32] Broken pipe
```

Some more information about my workspace
- Server: CherryPy 3.2.3
- Self Signed SSL Certificate
- ws4py version 0.3.4
- Edit: Python version 2.7.6

Note: There are no issues with `ws://`, hopefully this is the right place to report my issue.

Thanks for creating and maintaining such an awesome project btw!

**Comment by tito** [comment]
Fixed in cherrypy source, we can close it.
