### ISSUE TITLE
low priority: wsgiref example doesn't work

### ISSUE THREAD

**Issue by Seanny123** [Lawouach/WebSocket-for-Python#145]
From the documentation I extracted this example:
```
from wsgiref.simple_server import make_server
from ws4py.websocket import EchoWebSocket
from ws4py.server.wsgirefserver import WSGIServer, WebSocketWSGIRequestHandler
from ws4py.server.wsgiutils import WebSocketWSGIApplication

server = make_server('', 9000, server_class=WSGIServer,
                     handler_class=WebSocketWSGIRequestHandler,
                     app=WebSocketWSGIApplication(handler_cls=EchoWebSocket))
server.initialize_websockets_manager()
server.serve_forever()
```

However, when I run it, I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/ws4py/server/wsgiutils.py", line 101, in __call__
    raise HandshakeError('Header %s is not defined' % key)
HandshakeError: Header HTTP_UPGRADE is not defined
```

This seems to be some weird header stuff that's a bit beyond my knowledge level and might not even be the fault of ws4py. Additionally, this isn't really that big of a deal, since the built-in CherryPy example works great, so I'm going to go with that for now. Just thought I would mention it for future reference.

**Comment by anuragjain92** [comment]
make  change ' '  to 'localhost'
