### ISSUE TITLE
Client connection hangs when using Cherrypy

### ISSUE THREAD

**Issue by airqnetworks** [Lawouach/WebSocket-for-Python#146]
Hi,
I'm adding support to ws4py in an existing cherrpy application. I'm following the example in the documentation. 
I'm experiencing this problem. Sometime, client connection hangs and the server generates this exception:

``` python
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build/bdist.macosx-10.9-intel/egg/ws4py/manager.py", line 298, in run
    polled = self.poller.poll()
  File "build/bdist.macosx-10.9-intel/egg/ws4py/manager.py", line 96, in poll
    r, w, x = select.select(self._fds, [], [], self.timeout)
error: (9, 'Bad file descriptor')
```

This happens on MacOS X 10.9, Python 2.7 and CherryPy 3.6

Carmine

**Comment by tito** [comment]
Now, selectors are within a try/catch. Please reopen if you hit the exact same issue with new version (> 0.3.5 or master)
