### ISSUE TITLE
In opened(), closing connection would crash the server

### ISSUE THREAD

**Issue by millerf** [Lawouach/WebSocket-for-Python#159]
I think the title sums it up.

I need to kick out clients when IP address is duplicated (cannot connect twice with the same IP)

This is a pat of the dump

File "/Users/millerf/Documents/www/Python/mzk_local/mzk_local/mozaikserver/websocketendpoint.py", line 44, in opened
    self.close(error.code,error.message)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ws4py/websocket.py", line 176, in close
    self._write(self.stream.close(code=code, reason=reason).single(mask=self.stream.always_mask))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ws4py/streaming.py", line 141, in close
    return CloseControlMessage(code=code, reason=reason)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ws4py/messaging.py", line 145, in __init__
    data += struct.pack("!H", code)
error: integer out of range for 'H' format code 

Does it make any sense?

**Comment by millerf** [comment]
Same error using gevent or wsgiref servers

**Comment by millerf** [comment]
I tried the example for cherrypi, I cannot connect any client (in python or browser)


Traceback (most recent call last):
  File "tests/test_client_ws.py", line 20, in <module>
    ws.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ws4py/client/__init__.py", line 231, in connect
    self.process_response_line(response_line)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ws4py/client/__init__.py", line 284, in process_response_line
    raise HandshakeError("Invalid response status: %s %s" % (code, status))
ws4py.exc.HandshakeError: Invalid response status: 200 OK
