### ISSUE TITLE
HandshakeError: Header HTTP_UPGRADE is not defined

### ISSUE THREAD

**Issue by jcubic** [Lawouach/WebSocket-for-Python#184]
I've run wsgiref example code with this JS:

```javascript
 var connection = new WebSocket('ws://localhost:9000/');
  connection.onmessage = function(e) {
    console.log('Server: ' + e.data);
  };
  connection.onopen = function() {
    connection.send(JSON.stringify({message: 'hello'}));
  };
```
I I've got this error but the socket is working, I get `{message: 'hello'}` in response.

**Comment by TheSpeedyBlur** [comment]
Hey @jcubic,

> I've got this error

What error?

**Comment by jcubic** [comment]
It was year ago, probably the error from the title.

**Comment by TheSpeedyBlur** [comment]
Whoops, didn't see the timestamp :P

**Comment by MRZA-MRZA** [comment]
I faced the same error when using wsgiref example with apache and nginx:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/pi/.local/lib/python3.5/site-packages/ws4py/server/wsgiutils.py", line 101, in __call__
    raise HandshakeError('Header %s is not defined' % key)
ws4py.exc.HandshakeError: Header HTTP_UPGRADE is not defined
```
