### ISSUE TITLE
 [WinError 10061]

### ISSUE THREAD

**Issue by mohamedzeton** [Lawouach/WebSocket-for-Python#266]
hello guys i just bought a app from a website its a genrator accounts thing 
it gen accounts what ever when i start it i get this errore the app crash fast and i cant even copy the erorre and i tried and got this errore i tried restart my nothing worked and i think the webstie i bought from used python 

and its not a problem from the app i got the last update and my friends work for him good only me any help pls 

errore is 
Traceback (most recent call last):
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by Mart-Bogdan** [comment]
You should ask support at site that sold you that app.

P.S. can't see what it has to do with this project, there are no WebSocket-for-Python in Traceback
